-- MySQL Script generated by MySQL Workbench
-- Mon Mar 30 21:14:44 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departamento` (
  `idDepartamento` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Campus` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDepartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `idProfessor` INT NOT NULL,
  `Departamento_idDepartamento` INT NOT NULL,
  `Registro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProfessor`, `Departamento_idDepartamento`),
  INDEX `fk_Professor_Departamento1_idx` (`Departamento_idDepartamento` ASC) VISIBLE,
  CONSTRAINT `fk_Professor_Departamento1`
    FOREIGN KEY (`Departamento_idDepartamento`)
    REFERENCES `mydb`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa` (
  `idPessoa` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `CPF` INT NOT NULL,
  `Endereço` VARCHAR(45) NOT NULL,
  `Professor_idProfessor` INT NOT NULL,
  `Professor_Departamento_idDepartamento` INT NOT NULL,
  PRIMARY KEY (`idPessoa`, `Professor_idProfessor`, `Professor_Departamento_idDepartamento`),
  INDEX `fk_Pessoa_Professor1_idx` (`Professor_idProfessor` ASC, `Professor_Departamento_idDepartamento` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoa_Professor1`
    FOREIGN KEY (`Professor_idProfessor` , `Professor_Departamento_idDepartamento`)
    REFERENCES `mydb`.`Professor` (`idProfessor` , `Departamento_idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aluno` (
  `idAluno` INT NOT NULL,
  `Professor_idProfessor` INT NOT NULL,
  `Pessoa_idPessoa` INT NOT NULL,
  `Matrícula` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAluno`, `Professor_idProfessor`, `Pessoa_idPessoa`),
  INDEX `fk_Aluno_Professor1_idx` (`Professor_idProfessor` ASC) VISIBLE,
  INDEX `fk_Aluno_Pessoa1_idx` (`Pessoa_idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_Professor1`
    FOREIGN KEY (`Professor_idProfessor`)
    REFERENCES `mydb`.`Professor` (`idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `mydb`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Disciplina` (
  `idDisciplina` INT NOT NULL,
  `Professor_idProfessor` INT NOT NULL,
  PRIMARY KEY (`idDisciplina`, `Professor_idProfessor`),
  INDEX `fk_Disciplina_Professor1_idx` (`Professor_idProfessor` ASC) VISIBLE,
  CONSTRAINT `fk_Disciplina_Professor1`
    FOREIGN KEY (`Professor_idProfessor`)
    REFERENCES `mydb`.`Professor` (`idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Matriculado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Matriculado` (
  `Aluno_idAluno` INT NOT NULL,
  `Disciplina_idDisciplina` INT NOT NULL,
  PRIMARY KEY (`Aluno_idAluno`, `Disciplina_idDisciplina`),
  INDEX `fk_Aluno_has_Disciplina_Disciplina1_idx` (`Disciplina_idDisciplina` ASC) VISIBLE,
  INDEX `fk_Aluno_has_Disciplina_Aluno_idx` (`Aluno_idAluno` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_has_Disciplina_Aluno`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `mydb`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_has_Disciplina_Disciplina1`
    FOREIGN KEY (`Disciplina_idDisciplina`)
    REFERENCES `mydb`.`Disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Curso` (
  `idCurso` INT NOT NULL,
  `Departamento_idDepartamento` INT NOT NULL,
  PRIMARY KEY (`idCurso`, `Departamento_idDepartamento`),
  INDEX `fk_Curso_Departamento1_idx` (`Departamento_idDepartamento` ASC) VISIBLE,
  CONSTRAINT `fk_Curso_Departamento1`
    FOREIGN KEY (`Departamento_idDepartamento`)
    REFERENCES `mydb`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pré-requisitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pré-requisitos` (
  `idPré-requisitos` INT NOT NULL,
  PRIMARY KEY (`idPré-requisitos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Disciplia e Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Disciplia e Curso` (
  `Curso_idCurso` INT NOT NULL,
  `Disciplina_idDisciplina` INT NOT NULL,
  PRIMARY KEY (`Curso_idCurso`, `Disciplina_idDisciplina`),
  INDEX `fk_Curso_has_Disciplina_Disciplina1_idx` (`Disciplina_idDisciplina` ASC) VISIBLE,
  INDEX `fk_Curso_has_Disciplina_Curso1_idx` (`Curso_idCurso` ASC) VISIBLE,
  CONSTRAINT `fk_Curso_has_Disciplina_Curso1`
    FOREIGN KEY (`Curso_idCurso`)
    REFERENCES `mydb`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Curso_has_Disciplina_Disciplina1`
    FOREIGN KEY (`Disciplina_idDisciplina`)
    REFERENCES `mydb`.`Disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pré-requisitos das Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pré-requisitos das Disciplina` (
  `Disciplina_idDisciplina` INT NOT NULL,
  `Pré-requisitos_idPré-requisitos` INT NOT NULL,
  PRIMARY KEY (`Disciplina_idDisciplina`, `Pré-requisitos_idPré-requisitos`),
  INDEX `fk_Disciplina_has_Pré-requisitos_Pré-requisitos1_idx` (`Pré-requisitos_idPré-requisitos` ASC) VISIBLE,
  INDEX `fk_Disciplina_has_Pré-requisitos_Disciplina1_idx` (`Disciplina_idDisciplina` ASC) VISIBLE,
  CONSTRAINT `fk_Disciplina_has_Pré-requisitos_Disciplina1`
    FOREIGN KEY (`Disciplina_idDisciplina`)
    REFERENCES `mydb`.`Disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Disciplina_has_Pré-requisitos_Pré-requisitos1`
    FOREIGN KEY (`Pré-requisitos_idPré-requisitos`)
    REFERENCES `mydb`.`Pré-requisitos` (`idPré-requisitos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Período`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Período` (
  `idPeríodo` INT NOT NULL,
  `Ano` VARCHAR(45) NULL,
  `Semestre` VARCHAR(45) NULL,
  PRIMARY KEY (`idPeríodo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Oferta de Período`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Oferta de Período` (
  `Disciplina_idDisciplina` INT NOT NULL,
  `Disciplina_Professor_idProfessor` INT NOT NULL,
  `Período_idPeríodo` INT NOT NULL,
  PRIMARY KEY (`Disciplina_idDisciplina`, `Disciplina_Professor_idProfessor`, `Período_idPeríodo`),
  INDEX `fk_Disciplina_has_Período_Período1_idx` (`Período_idPeríodo` ASC) VISIBLE,
  INDEX `fk_Disciplina_has_Período_Disciplina1_idx` (`Disciplina_idDisciplina` ASC, `Disciplina_Professor_idProfessor` ASC) VISIBLE,
  CONSTRAINT `fk_Disciplina_has_Período_Disciplina1`
    FOREIGN KEY (`Disciplina_idDisciplina` , `Disciplina_Professor_idProfessor`)
    REFERENCES `mydb`.`Disciplina` (`idDisciplina` , `Professor_idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Disciplina_has_Período_Período1`
    FOREIGN KEY (`Período_idPeríodo`)
    REFERENCES `mydb`.`Período` (`idPeríodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aluno_matriculado_Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aluno_matriculado_Curso` (
  `Aluno_idAluno` INT NOT NULL,
  `Aluno_Professor_idProfessor` INT NOT NULL,
  `Aluno_Pessoa_idPessoa` INT NOT NULL,
  `Curso_idCurso` INT NOT NULL,
  PRIMARY KEY (`Aluno_idAluno`, `Aluno_Professor_idProfessor`, `Aluno_Pessoa_idPessoa`, `Curso_idCurso`),
  INDEX `fk_Aluno_has_Curso_Curso1_idx` (`Curso_idCurso` ASC) VISIBLE,
  INDEX `fk_Aluno_has_Curso_Aluno1_idx` (`Aluno_idAluno` ASC, `Aluno_Professor_idProfessor` ASC, `Aluno_Pessoa_idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_has_Curso_Aluno1`
    FOREIGN KEY (`Aluno_idAluno` , `Aluno_Professor_idProfessor` , `Aluno_Pessoa_idPessoa`)
    REFERENCES `mydb`.`Aluno` (`idAluno` , `Professor_idProfessor` , `Pessoa_idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_has_Curso_Curso1`
    FOREIGN KEY (`Curso_idCurso`)
    REFERENCES `mydb`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Extensão`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Extensão` (
  `idExtensão` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Instituição` VARCHAR(45) NOT NULL,
  `Área` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idExtensão`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Extensão_has_Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Extensão_has_Aluno` (
  `Extensão_idExtensão` INT NOT NULL,
  `Aluno_idAluno` INT NOT NULL,
  PRIMARY KEY (`Extensão_idExtensão`, `Aluno_idAluno`),
  INDEX `fk_Extensão_has_Aluno_Aluno1_idx` (`Aluno_idAluno` ASC) VISIBLE,
  INDEX `fk_Extensão_has_Aluno_Extensão1_idx` (`Extensão_idExtensão` ASC) VISIBLE,
  CONSTRAINT `fk_Extensão_has_Aluno_Extensão1`
    FOREIGN KEY (`Extensão_idExtensão`)
    REFERENCES `mydb`.`Extensão` (`idExtensão`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Extensão_has_Aluno_Aluno1`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `mydb`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente PJ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente PJ` (
  `idCliente` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Endereço` VARCHAR(45) NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  PRIMARY KEY (`idCliente`, `Pedido_idPedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Entrega` (
  `idEntrega` INT NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `Cógido de Rastreio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEntrega`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente PF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente PF` (
  `idCliente PF` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Endereço` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente PF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `idPedido` INT NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `Descrição` VARCHAR(45) NULL,
  `Cliente PJ id` INT NOT NULL,
  `Frete` VARCHAR(45) NULL,
  `Entrega id` INT NOT NULL,
  `Cliente PF id` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `Cliente PJ id`, `Entrega id`, `Cliente PF id`),
  INDEX `fk_Pedido_Cliente1_idx` (`Cliente PJ id` ASC) VISIBLE,
  INDEX `fk_Pedido_Entrega1_idx` (`Entrega id` ASC) VISIBLE,
  INDEX `fk_Pedido_Cliente PF1_idx` (`Cliente PF id` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente PJ id`)
    REFERENCES `mydb`.`Cliente PJ` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Entrega1`
    FOREIGN KEY (`Entrega id`)
    REFERENCES `mydb`.`Entrega` (`idEntrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Cliente PF1`
    FOREIGN KEY (`Cliente PF id`)
    REFERENCES `mydb`.`Cliente PF` (`idCliente PF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `idProduto` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Categoria` VARCHAR(45) NULL,
  `Valor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estoque` (
  `idEstoque` INT NOT NULL,
  `Quantidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstoque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor` (
  `idFornecedor` INT NOT NULL,
  `CNPJ` VARCHAR(45) NOT NULL,
  `Razão Social` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido contém Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido contém Produtos` (
  `Produto_idProduto` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  PRIMARY KEY (`Produto_idProduto`, `Pedido_idPedido`),
  INDEX `fk_Produto_has_Pedido_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  INDEX `fk_Produto_has_Pedido_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Pedido_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `mydb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto Disponível`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto Disponível` (
  `Produto_idProduto` INT NOT NULL,
  `Fornecedor_idFornecedor` INT NOT NULL,
  PRIMARY KEY (`Produto_idProduto`, `Fornecedor_idFornecedor`),
  INDEX `fk_Produto_has_Fornecedor_Fornecedor1_idx` (`Fornecedor_idFornecedor` ASC) VISIBLE,
  INDEX `fk_Produto_has_Fornecedor_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Fornecedor_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Fornecedor_Fornecedor1`
    FOREIGN KEY (`Fornecedor_idFornecedor`)
    REFERENCES `mydb`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estoque_has_Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estoque_has_Produto` (
  `Estoque_idEstoque` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  PRIMARY KEY (`Estoque_idEstoque`, `Produto_idProduto`),
  INDEX `fk_Estoque_has_Produto_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  INDEX `fk_Estoque_has_Produto_Estoque1_idx` (`Estoque_idEstoque` ASC) VISIBLE,
  CONSTRAINT `fk_Estoque_has_Produto_Estoque1`
    FOREIGN KEY (`Estoque_idEstoque`)
    REFERENCES `mydb`.`Estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estoque_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Terceiro Vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Terceiro Vendedor` (
  `idTerceiro Vendedor` INT NOT NULL,
  `Razão Social` VARCHAR(45) NULL,
  `Local` VARCHAR(45) NULL,
  PRIMARY KEY (`idTerceiro Vendedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produtos Vendido por Terceiros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produtos Vendido por Terceiros` (
  `Terceiro Vendedor_idTerceiro Vendedor` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  `Quantidade` VARCHAR(45) NULL,
  PRIMARY KEY (`Terceiro Vendedor_idTerceiro Vendedor`, `Produto_idProduto`),
  INDEX `fk_Terceiro Vendedor_has_Produto_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  INDEX `fk_Terceiro Vendedor_has_Produto_Terceiro Vendedor1_idx` (`Terceiro Vendedor_idTerceiro Vendedor` ASC) VISIBLE,
  CONSTRAINT `fk_Terceiro Vendedor_has_Produto_Terceiro Vendedor1`
    FOREIGN KEY (`Terceiro Vendedor_idTerceiro Vendedor`)
    REFERENCES `mydb`.`Terceiro Vendedor` (`idTerceiro Vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Terceiro Vendedor_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pagamento` (
  `idPagamento` INT NOT NULL,
  `Cartão de Crédito` VARCHAR(45) NULL,
  `Cartão de Débito` VARCHAR(45) NULL,
  `PIX` VARCHAR(45) NULL,
  `Dinheiro` VARCHAR(45) NULL,
  `Pedido id` INT NOT NULL,
  `Cliente PJ id` INT NOT NULL,
  `Cliente PF id` INT NOT NULL,
  `Data do Pagamento` DATE NULL,
  PRIMARY KEY (`idPagamento`, `Pedido id`, `Cliente PJ id`, `Cliente PF id`),
  INDEX `fk_Pagamento_Pedido1_idx` (`Pedido id` ASC) VISIBLE,
  INDEX `fk_Pagamento_Cliente1_idx` (`Cliente PJ id` ASC) VISIBLE,
  INDEX `fk_Pagamento_Cliente PF1_idx` (`Cliente PF id` ASC) VISIBLE,
  CONSTRAINT `fk_Pagamento_Pedido1`
    FOREIGN KEY (`Pedido id`)
    REFERENCES `mydb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pagamento_Cliente1`
    FOREIGN KEY (`Cliente PJ id`)
    REFERENCES `mydb`.`Cliente PJ` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pagamento_Cliente PF1`
    FOREIGN KEY (`Cliente PF id`)
    REFERENCES `mydb`.`Cliente PF` (`idCliente PF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Manutenção`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Manutenção` (
  `idManutenção` INT NOT NULL,
  PRIMARY KEY (`idManutenção`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Revisão`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Revisão` (
  `idRevisão` INT NOT NULL,
  PRIMARY KEY (`idRevisão`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Endereço` VARCHAR(45) NOT NULL,
  `CPF` INT NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipe de Mecânicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipe de Mecânicos` (
  `idEquipe de Mecânicos` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Especialidade` VARCHAR(45) NOT NULL,
  `Código` VARCHAR(45) NOT NULL,
  `Endereço` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEquipe de Mecânicos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Autorização OS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Autorização OS` (
  `idAutorização OS` INT NOT NULL,
  `Data de Emissão` DATE NULL,
  `Tipo de Serviço` VARCHAR(45) NULL,
  `Autorização OScol` VARCHAR(45) NOT NULL,
  `Valor` VARCHAR(45) NOT NULL,
  `Equipe de Mecânicos ID` INT NOT NULL,
  `Cliente ID` INT NOT NULL,
  PRIMARY KEY (`idAutorização OS`, `Equipe de Mecânicos ID`, `Cliente ID`),
  INDEX `fk_Autorização OS_Cliente1_idx` (`Cliente ID` ASC) VISIBLE,
  INDEX `fk_Autorização OS_Equipe de Mecânicos1_idx` (`Equipe de Mecânicos ID` ASC) VISIBLE,
  CONSTRAINT `fk_Autorização OS_Cliente1`
    FOREIGN KEY (`Cliente ID`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Autorização OS_Equipe de Mecânicos1`
    FOREIGN KEY (`Equipe de Mecânicos ID`)
    REFERENCES `mydb`.`Equipe de Mecânicos` (`idEquipe de Mecânicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ordem de Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ordem de Serviço` (
  `idOrdem de Serviço` INT NOT NULL,
  `Data de Entrega` DATE NOT NULL,
  `Valor do Serviço` VARCHAR(45) NOT NULL,
  `Valor das peças` VARCHAR(45) NOT NULL,
  `Data de Emissão` DATE NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `Equipe de Mecânicos ID` INT NOT NULL,
  `Autorização OS ID` INT NOT NULL,
  PRIMARY KEY (`idOrdem de Serviço`, `Equipe de Mecânicos ID`, `Autorização OS ID`),
  INDEX `fk_Ordem de Serviço_Autorização OS1_idx` (`Autorização OS ID` ASC) VISIBLE,
  INDEX `fk_Ordem de Serviço_Equipe de Mecânicos1_idx` (`Equipe de Mecânicos ID` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem de Serviço_Autorização OS1`
    FOREIGN KEY (`Autorização OS ID`)
    REFERENCES `mydb`.`Autorização OS` (`idAutorização OS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem de Serviço_Equipe de Mecânicos1`
    FOREIGN KEY (`Equipe de Mecânicos ID`)
    REFERENCES `mydb`.`Equipe de Mecânicos` (`idEquipe de Mecânicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carro` (
  `idCarro` INT NOT NULL,
  `Placa` VARCHAR(45) NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `Ano` VARCHAR(45) NOT NULL,
  `Cliente ID` INT NOT NULL,
  `Mecânicos ID` INT NOT NULL,
  PRIMARY KEY (`idCarro`, `Cliente ID`, `Mecânicos ID`),
  INDEX `fk_Carro_Cliente1_idx` (`Cliente ID` ASC) VISIBLE,
  INDEX `fk_Carro_Equipe de Mecânicos1_idx` (`Mecânicos ID` ASC) VISIBLE,
  CONSTRAINT `fk_Carro_Cliente1`
    FOREIGN KEY (`Cliente ID`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carro_Equipe de Mecânicos1`
    FOREIGN KEY (`Mecânicos ID`)
    REFERENCES `mydb`.`Equipe de Mecânicos` (`idEquipe de Mecânicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipe de Mecânicos Executa Revisão`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipe de Mecânicos Executa Revisão` (
  `Equipe de Mecânicos ID` INT NOT NULL,
  `Revisão ID` INT NOT NULL,
  PRIMARY KEY (`Equipe de Mecânicos ID`, `Revisão ID`),
  INDEX `fk_Equipe de Mecânicos_has_Revisão_Revisão1_idx` (`Revisão ID` ASC) VISIBLE,
  INDEX `fk_Equipe de Mecânicos_has_Revisão_Equipe de Mecânicos1_idx` (`Equipe de Mecânicos ID` ASC) VISIBLE,
  CONSTRAINT `fk_Equipe de Mecânicos_has_Revisão_Equipe de Mecânicos1`
    FOREIGN KEY (`Equipe de Mecânicos ID`)
    REFERENCES `mydb`.`Equipe de Mecânicos` (`idEquipe de Mecânicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipe de Mecânicos_has_Revisão_Revisão1`
    FOREIGN KEY (`Revisão ID`)
    REFERENCES `mydb`.`Revisão` (`idRevisão`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipe de Mecânicos Executa Manutenção`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipe de Mecânicos Executa Manutenção` (
  `Equipe de Mecânicos ID` INT NOT NULL,
  `Manutenção ID` INT NOT NULL,
  PRIMARY KEY (`Equipe de Mecânicos ID`, `Manutenção ID`),
  INDEX `fk_Equipe de Mecânicos_has_Manutenção_Manutenção1_idx` (`Manutenção ID` ASC) VISIBLE,
  INDEX `fk_Equipe de Mecânicos_has_Manutenção_Equipe de Mecânic_idx` (`Equipe de Mecânicos ID` ASC) VISIBLE,
  CONSTRAINT `fk_Equipe de Mecânicos_has_Manutenção_Equipe de Mecânicos1`
    FOREIGN KEY (`Equipe de Mecânicos ID`)
    REFERENCES `mydb`.`Equipe de Mecânicos` (`idEquipe de Mecânicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipe de Mecânicos_has_Manutenção_Manutenção1`
    FOREIGN KEY (`Manutenção ID`)
    REFERENCES `mydb`.`Manutenção` (`idManutenção`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
